on:
  push:
    branches: ["*"]
    tags: ["*"]

jobs:
  build:
    strategy:
      matrix:
        node-version: [19]  # TODO: Add LTS
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: yarn
    - run: yarn install --immutable  # TODO: cache and apply --immutable-cache --check-cache
    - run: yarn build
    - run: yarn test
    - run: yarn pack-all

  libplanet-tools-npm-install-test:
    name: "@planetarium/cli installation test"
    strategy:
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
        - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - id: latest-tag
      name: Get the latest tag
      uses: WyriHaximus/github-action-get-previous-tag@v1
      with:
        fallback: 0.27.3
    - if: runner.os != 'Windows'
      run: |
        set -ev
        cd Libplanet.Tools/
        bin/npm-test.sh "$LATEST_VERSION"
      env:
        LATEST_VERSION: ${{ steps.latest-tag.outputs.tag }}
    - if: runner.os == 'Windows'
      run: |
        $ErrorActionPreference = "Stop"
        cd Libplanet.Tools\
        powershell `
          -ExecutionPolicy Bypass `
          -File bin\npm-test.ps1 `
          -Version $env:LATEST_VERSION
      env:
        LATEST_VERSION: ${{ steps.latest-tag.outputs.tag }}
